#spring.datasource.url= jdbc:postgresql://localhost:5432/api-gateway
#spring.datasource.username=postgres
#spring.datasource.password=1234
#spring.jpa.hibernate.ddl-auto=update
#
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/api-gateway
    username: postgres
    password: 1234
server:
  port: 8080
  
  
  
  
  
  
  
  
  
  